### ISSUE TITLE
Smile in percent

### ISSUE THREAD

**Issue by nimaltd** [aquibjaved/Smile-Recognition-#1]
Hello. Can i get smile in percent?

**Comment by aquibjaved** [comment]
@nimaltd  Hi, yes 
the line `y = tf.nn.softmax(tf.matmul(x_, W) + b)` if you run this `sess.run(y)`  this give you probability for bot neutral and smile.

**Comment by nimaltd** [comment]
Thank you.  I want run opencv on nanopi for first time.  I never work with python and embedded linux. 
I try to run. Can i ask you ,If i have a problem ?

**Comment by nimaltd** [comment]
Python 2.7.13 (default, Nov 24 2017, 17:33:09) 
[GCC 6.3.0 20170516] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> 
 RESTART: /home/pi/Downloads/Real-time-Smile-Recognition-master/final_smile.py 

Traceback (most recent call last):
  File "/home/pi/Downloads/Real-time-Smile-Recognition-master/final_smile.py", line 9, in <module>
    svc_1 = joblib.load('smile.joblib.pkl')
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 577, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/lib/python2.7/dist-packages/joblib/numpy_pickle.py", line 507, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
KeyError: '\x00'
>>> 


hello again. what is that problem. I cant run it.

**Comment by vaishnavi-2901** [comment]
hi there!!
i got same answer every time, can you help me out?

**Comment by aquibjaved** [comment]
Did you check your training accuracy, confusion matrix on the test data?

**Comment by vaishnavi-2901** [comment]
Yes I checked
But it is producing 0 in index and giving me same answer repeatedly.

**Comment by aquibjaved** [comment]
While testing? 
Can you the confusion matrix, please.

**Comment by vaishnavi-2901** [comment]
I didn't use confusion metrics.
I just use your part-1 code for the 5 emotions i.e. angry,  fear,  happy,
neutral, sad
And I got some errors.
I am getting
W1: [0.....0]
And bias =0
So is the indx.

**Comment by vishu1089** [comment]
You can contact me at 7229942547
This is my Whatsapp no
I have a project to submit
And this code is the code, on which I put all my efforts as in debugging
and understanding the code for presentation.
Now,  I can not back out
So If you will help me,  this would be a great help!
And after that I have to implement my own algorithm and as a beginner I'm
getting so much problems.
I have to submit this before 5 April.
So, please help me!
Thanks!

**Comment by aquibjaved** [comment]
Aaah, 
So, you've 5 classes. I am not sure the logistic regression (one layer neural network) will generalize well on five classes and also it depends on the size of data. 
you've to look for other approaches like CNN based classifier.

**Comment by vaishnavi-2901** [comment]
Help me :(
I really don't know about cnn
And I don't have so much time to do this.
And even when I was doing the same code for two classes
It wasn't working.

**Comment by aquibjaved** [comment]
@vishu1089  
This is a public platform, please be careful while sharing your personal details (Phone number) please delete.

**Comment by vaishnavi-2901** [comment]
Can I share my code and data...
It is not so large... If you're free and willing to solve my problem
Please do check it. :))

**Comment by vaishnavi-2901** [comment]
Ok
Thanks

**Comment by vaishnavi-2901** [comment]
w1: [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 ...
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
bias: [0. 0. 0. 0. 0.]
i'm getting this for every input.

**Comment by aquibjaved** [comment]
Here is a list of the same project, you can try their codes:

- `http://www.paulvangent.com/2016/08/05/emotion-recognition-using-facial-landmarks/`
- `https://appliedmachinelearning.blog/2018/11/28/demonstration-of-facial-emotion-recognition-on-real-time-video-using-cnn-python-keras/`
- `https://github.com/amineHorseman/facial-expression-recognition-using-cnn`

**Comment by aquibjaved** [comment]
Below are the list of the same project, you can try their codes:

- http://www.paulvangent.com/2016/08/05/emotion-recognition-using-facial-landmarks/
- https://appliedmachinelearning.blog/2018/11/28/demonstration-of-facial-emotion-recognition-on-real-time-video-using-cnn-python-keras/
- https://github.com/amineHorseman/facial-expression-recognition-using-cnn

**Comment by vaishnavi-2901** [comment]
Thanks
